apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefiles
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  azureFile:
    secretName: backendsecret
    shareName: session-exports
    readOnly: false
  claimRef:
    namespace: default
    name: azure-fileshare
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: azure-fileshare
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
