apiVersion: apps/v1
kind: Deployment
metadata:
    name: sessions-api
    labels:
        tier: backend
        app: sessions
        ms: sessions
spec:
    replicas: 3
    selector:
        matchLabels:
         app: sessions
         tier: backend
         ms: sessions
    template:
        metadata:
            name: sessions-ms
            labels:
                app: sessions
                tier: backend
                ms: sessions
        spec:
            containers:
                - name: sesssions-microservice
                  image: thhdemo.azurecr.io/sessions-api:0.0.7
                  env:
                    - name: ASPNETCORE_URLS
                      value: http://*:8080
                    - name: DbConnectionString
                      valueFrom:
                        secretKeyRef:
                          name: backendsecret
                          key: db
                  ports:
                    - containerPort: 8080
                  livenessProbe:
                    httpGet:
                      path: /api/meta/healthy
                      port: 8080
                    initialDelaySeconds: 30
                    timeoutSeconds: 4
                    periodSeconds: 5
                  readinessProbe:
                    httpGet:
                      path: /api/meta/ready
                      port: 8080
                    initialDelaySeconds: 30
                    timeoutSeconds: 4
                    periodSeconds: 5
                  resources:
                    requests:
                      memory: "64Mi"
                      cpu: "64m"
                    limits:
                      memory: "96Mi"
                      cpu: "125m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: votings-api
    labels:
        tier: backend
        app: sessions
        ms: votings
spec:
    replicas: 3
    selector:
        matchLabels:
         app: sessions
         tier: backend
         ms: votings
    template:
        metadata:
            name: votings-ms
            labels:
                app: sessions
                tier: backend
                ms: votings
        spec:
            containers:
                - name: votings-microservice
                  image: thhdemo.azurecr.io/votings-api:0.0.3
                  env:
                    - name: ASPNETCORE_URLS
                      value: http://*:8080
                    - name: DbConnectionString
                      valueFrom:
                        secretKeyRef:
                          name: backendsecret
                          key: db
                  ports:
                    - containerPort: 8080
                  livenessProbe:
                    httpGet:
                      path: /api/meta/healthy
                      port: 8080
                    initialDelaySeconds: 30
                    timeoutSeconds: 4
                    periodSeconds: 5
                  readinessProbe:
                    httpGet:
                      path: /api/meta/ready
                      port: 8080
                    initialDelaySeconds: 30
                    timeoutSeconds: 4
                    periodSeconds: 5
                  resources:
                    requests:
                      memory: "64Mi"
                      cpu: "64m"
                    limits:
                      memory: "96Mi"
                      cpu: "125m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: export-api
    labels:
        tier: backend
        app: sessions
        ms: export
spec:
    replicas: 3
    selector:
        matchLabels:
         app: sessions
         tier: backend
         ms: export
    template:
        metadata:
            name: export-ms
            labels:
                app: sessions
                tier: backend
                ms: export
        spec:
            containers:
                - name: export-microservice
                  image: thhdemo.azurecr.io/export-api:0.0.1
                  env:
                    - name: ASPNETCORE_URLS
                      value: http://*:8080
                  ports:
                    - containerPort: 8080
                  livenessProbe:
                    httpGet:
                      path: /api/meta/healthy
                      port: 8080
                    initialDelaySeconds: 30
                    timeoutSeconds: 4
                    periodSeconds: 5
                  readinessProbe:
                    httpGet:
                      path: /api/meta/ready
                      port: 8080
                    initialDelaySeconds: 30
                    timeoutSeconds: 4
                    periodSeconds: 5
                  resources:
                    requests:
                      memory: "64Mi"
                      cpu: "64m"
                    limits:
                      memory: "96Mi"
                      cpu: "125m"
