apiVersion: v1
kind: Secret
metadata:
    name: backendsecret
type: Opaque
data:
    db: <<base64 encoded connectionstring here>>
    sqlHost: <<base64 encoded SQL Azure Host here>>
    sqlUser: <<base64 encoded SQL Azure User here>>
    sqlPwd: <<base64 encoded SQL Azure PWD here>>
    mailGunDomain: <<base64 encoded MailGun Domain here>>
    mailGunApiKey: <<base64 encoded MailGun ApiKey here>>
    azStorageAccount: <<base64 encoded Storage Account Name  here>>
    azStorageAcccountKey: <<base64 encoded Storage Account Key here>>
