apiVersion: apps/v1
kind: Deployment
metadata:
    name: sessions-ms-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            tier: backend
            ms: sessions
    template:
        metadata:
            labels:
                tier: backend
                ms: sessions
        spec:
            containers:
                - name: sesssions-microservice
                  image: thhdemo.azurecr.io/sessions-ms:latest
                  env:
                      - name: APPINSIGHTS_INSTRUMENTATIONKEY
                        valueFrom:
                            secretKeyRef:
                                name: backendsecret
                                key: ai_key
                      - name: ASPNETCORE_URLS
                        value: http://*:8080
                      - name: DbConnectionString
                        valueFrom:
                            secretKeyRef:
                                name: backendsecret
                                key: db
                  ports:
                      - containerPort: 8080
                  livenessProbe:
                      httpGet:
                          path: /api/meta/healthy
                          port: 8080
                      initialDelaySeconds: 30
                      timeoutSeconds: 4
                      periodSeconds: 5
                  readinessProbe:
                      httpGet:
                          path: /api/meta/ready
                          port: 8080
                      initialDelaySeconds: 30
                      timeoutSeconds: 4
                      periodSeconds: 5
                  resources:
                      requests:
                          memory: '64Mi'
                          cpu: '64m'
                      limits:
                          memory: '96Mi'
                          cpu: '125m'
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: votings-ms-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            tier: backend
            ms: votings
    template:
        metadata:
            name: votings-ms
            labels:
                tier: backend
                ms: votings
        spec:
            containers:
                - name: votings-microservice
                  image: thhdemo.azurecr.io/votings-ms:latest
                  env:
                      - name: APPINSIGHTS_INSTRUMENTATIONKEY
                        valueFrom:
                            secretKeyRef:
                                name: backendsecret
                                key: ai_key
                      - name: ASPNETCORE_URLS
                        value: http://*:8080
                      - name: DbConnectionString
                        valueFrom:
                            secretKeyRef:
                                name: backendsecret
                                key: db
                  ports:
                      - containerPort: 8080
                  livenessProbe:
                      httpGet:
                          path: /api/meta/healthy
                          port: 8080
                      initialDelaySeconds: 30
                      timeoutSeconds: 4
                      periodSeconds: 5
                  readinessProbe:
                      httpGet:
                          path: /api/meta/ready
                          port: 8080
                      initialDelaySeconds: 30
                      timeoutSeconds: 4
                      periodSeconds: 5
                  resources:
                      requests:
                          memory: '64Mi'
                          cpu: '64m'
                      limits:
                          memory: '96Mi'
                          cpu: '125m'

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: export-ms-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            tier: backend
            ms: export
    template:
        metadata:
            labels:
                tier: backend
                ms: export
        spec:
            volumes:
                - name: azurefileshare
                  azureFile:
                    secretName: backendsecret
                    shareName: session-exports
                    readOnly: false
            containers:
                - name: export-microservice
                  image: thhdemo.azurecr.io/export-ms:latest
                  env:
                      - name: APPINSIGHTS_INSTRUMENTATIONKEY
                        valueFrom:
                            secretKeyRef:
                                name: backendsecret
                                key: ai_key
                      - name: ASPNETCORE_URLS
                        value: http://*:8080
                      - name: DbConnectionString
                        valueFrom:
                            secretKeyRef:
                                name: backendsecret
                                key: db
                  ports:
                      - containerPort: 8080
                  volumeMounts:
                    - mountPath: "/var/session-exports"
                      name: azurefileshare
                  livenessProbe:
                      httpGet:
                          path: /api/meta/healthy
                          port: 8080
                      initialDelaySeconds: 10
                      timeoutSeconds: 2
                      periodSeconds: 30
                  readinessProbe:
                      httpGet:
                          path: /api/meta/ready
                          port: 8080
                      initialDelaySeconds: 10
                      timeoutSeconds: 5
                  resources:
                      requests:
                          memory: '64Mi'
                          cpu: '64m'
                      limits:
                          memory: '96Mi'
                          cpu: '125m'
---
