apiVersion: batch/v1beta1
kind: CronJob
metadata:
    name: auditlog-cleaner
spec:
    schedule: "* * * * *"
    jobTemplate:
        spec:
            template:
                spec:
                    restartPolicy: Never
                    containers:
                        - name: auditlog-cleaner
                          image: thhdemo.azurecr.io/auditlog-cleaner:latest
                          env:
                            - name: DbConnectionString
                              valueFrom:
                                secretKeyRef:
                                  name: backendsecret
                                  key: db
